Repository lucy-kim04/4-ViewMyStartup-team1-BE, pull requests merged in 2025-01, with the labels that each got.

#18 [김세환] getComapnies, getInvestments, createInvestment, deleteInvestment, patchInvestment API 구현 #17
  .DS_Store
  package-lock.json
  package.json
  server.js
  src/http/companies_ksh.http
  src/http/investments_ksh.http
  src/routes/createInvestment_ksh.js
  src/routes/deleteInvestment_ksh.js
  src/routes/getCompanies_ksh.js
  src/routes/getInvestments_ksh.js
  src/routes/patchInvestment_ksh.js
Labels: feat

#19 chore: 마이너 수정
  server.js
  src/data/mock.js
  src/http/companies_jhm.http
  src/http/users_jhm.http
  src/routes/getCompanyRank_jhm.js
  src/routes/getCompany_jhm.js
Labels: fix

#23 fix: investment 테이블에 '투자자 이름' 속성 추가
  src/data/mock.js
  src/routes/getCompany_jhm.js
  structs.js
Labels: fix

#24 [구은모] feat: getCompanies API 구현
  server.js
  src/http/companies_kem.http
  src/routes/getCompanies_Kem.js
Labels: feat, fix

#25 [김세환] investment 내 name 속성 추가
  src/http/investments_ksh.http
  src/routes/createInvestment_ksh.js
  src/routes/getInvestments_ksh.js
  src/routes/patchInvestment_ksh.js
Labels: fix

#26 feat: mock.js 수정(투자 목록 추가), 투자목록 조회 API 수정
  src/data/mock.js
  src/http/companies_jhm.http
  src/routes/getInvesterList_kjy.js
Labels: feat

#29 [김희주] fix: package.json에 schema추가
  package.json
Labels: fix

#32 [김희주] fix: server.js에 포트 설정 명확화
  server.js
Labels: fix

#33 [김희주] fix: PORT 변경
  server.js
Labels: fix

#34 [김희주] fix: PORT 부분 삭제
  server.js
Labels: fix

#35 [김희주] fix: 원상복귀
  package.json
Labels: fix
